### PR TITLE
!deploy 0.1.63

### PR DESCRIPTION
**Pull request by Dargmuesli**
Last deploy did not succeed. This one should be formatted correctly and update the manifest too.

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Haha, I trigger on `!Deploy` and appended `Deploy!` - my bad!  Closing this out, will toss a commit in and push a deployment later this evening, sorry about that!

**Comment by Dargmuesli** [comment]
Thanks

**Comment by Dargmuesli** [comment]
But please keep in mind to update the manifest too! ;)

**Comment by RamblingCookieMonster** [comment]
Deployed!

Updated it manually in case you were using it from GitHub - fyi the build process automatically checks for the next version to use and [bumps it before publishing](https://github.com/RamblingCookieMonster/PSDepend/blob/master/psake.ps1#L67)

Cheers!

**Comment by Dargmuesli** [comment]
Thank you! Nice, wasn't sure that works automatically here, but I guessed ;)

**Pull request closed without merging**
