### PR TITLE
Add AWS S3 bucket support #27

### PR DESCRIPTION
**Pull request by Sarafian**
As discussed in GH-27:
- New dependency type implementation for AWSS3Object
- New unit test for AWSS3Object. Mocked and Actual download from AWS S3
- Add AWSPowershell module to building prerequisites

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks for putting this together!

What version of pester are your tests targeting?  Guessing my hard coding version `3.4.2` might be throwing things off.  If that's the case, I can revisit failing tests on my side and use the latest pester.

Cheers!

**Comment by Sarafian** [comment]
I'm with `3.4.0` which is less than yours.

**Comment by Sarafian** [comment]
I've now updated to the latest version of Pester `4.0.2` and the AWSS3Object dependency scripts are successful. but if you update, you should expect these to fail:

```
 Describing Package Type PS5

    Context PackageSource does not Exist
      [+] Throws because Repository could not be found 876ms

    Context Same package version exists
      [-] Runs Get-Package and Find-Package, skips Install-Package 878ms
        Parameter set cannot be resolved using the specified named parameters.
        at line: 188 in C:\Users\Alex\Documents\Develop\GitHub\PSDepend\PSDepend\Public\Invoke-DependencyScript.ps1

    Context Test-Dependency
      [-] Returns $true when it finds an existing module 765ms
        Parameter set cannot be resolved using the specified named parameters.
        at line: 188 in C:\Users\Alex\Documents\Develop\GitHub\PSDepend\PSDepend\Public\Invoke-DependencyScript.ps1
      [-] Returns $false when it doesn't find an existing module 723ms
        Parameter set cannot be resolved using the specified named parameters.
        at line: 188 in C:\Users\Alex\Documents\Develop\GitHub\PSDepend\PSDepend\Public\Invoke-DependencyScript.ps1
      [+] Returns $false when it finds an existing module with a lower version 744ms
```

Overall, I'm not sure what the problem is with the broken tests as I can't reproduce on my side. The configured s3 object is `https://s3-eu-west-1.amazonaws.com/cloudformation-templates-eu-west-1/Windows_Single_Server_SharePoint_Foundation.template` which does not require authorization, so it should work well as a test. I've also run the tests without a profile with success.

**Comment by RamblingCookieMonster** [comment]
Hi!  Dropped the ball on this, apologies for the delay!  Will try to get the testing wrapped up today!

**Comment by RamblingCookieMonster** [comment]
Alrighty!  I think I have the tests ironed out (gating on Pester 4.02).  That whole Package test section needs to be redone, some serious ugliness due to [this bit](https://github.com/pester/Pester/issues/604) and my tendency to 'just get it working' vs. refactoring : )

Want to rebase, merge the build.ps1 conflict, and force push to your fork? That should bring things in line and let the tests start running.  Or, re-fork, add your new files, and add that AWSPowerShell line to the build.ps1, if that's easier.

Cheers!

**Comment by Sarafian** [comment]
Hi, no problem for the delay. If I remember correctly my changes to the codebase are very limited so conflict resolution will be very easy. Therefore I suggest to proceed with what did you the best.

**Comment by RamblingCookieMonster** [comment]
Whew!  Sorry about the half year wait : )  poked around at the tests, seem to have it working.

Can you (or anyone who sees this) run a quick test to see if it actually works?  Don't have an amazon account to play with at the moment

Cheers!

**Comment by Sarafian** [comment]
I had completely forgotten about this. In the meantime, I've worked a lot with the AWSPowerShell module and I'm not sure anymore if the approach could be that simple. Each AWSPowerShell cmdlets has a strange (for PowerShell) set optional parameter set to drive the authorization. I would now suggest that all such parameters are somehow optional from the config file. Don't know when I can improve upon this though.

**Comment by RamblingCookieMonster** [comment]
I'm going to close this out for now, feel free to re-open when you're ready!

**Pull request closed without merging**
