### PR TITLE
Adding support for pre-releases and semantic versioning (PowerShell Gallery)

### LINKED ISSUE #68: Add support for pre-Release versions
With the new AllowPrerelease switch, we can install pre-release modules.
It would be handy if we could express a dependency on such a pre-release module.

### PR DESCRIPTION
**Pull request by raandree**
This fixes #68.

The code of System.Management.Automation.SemanticVersion has been taken from PowerShell 7 and slightly modified to run in PowerShell 5.

Setting Pester version to 4.10.1 as the tests are not working with Pester 5.

### CODE REVIEW

**Comment by raandree** [comment]
One thing just came to my mind. This is a braking change that prevents working with 4-digit version numbers. I can do a TryPrase to identify the kind of version we are dealing with and cast either to System.Version or S.M.A.SemanticVersion. Let's wait with the merge.

**Comment by raandree** [comment]
@RamblingCookieMonster, I have added compatibility for versions and semantic versions in 'PSGalleryModule.ps1'. I have added tests as well.

**Comment by RamblingCookieMonster** [comment]
On a quick pass this lgtm, and looks like error handling will make it a non-breaking change (you had mentioned this above)?  If it's working for you, I'm good to merge!

**Comment by raandree** [comment]
Have just tested with the [DscWorkshop](https://github.com/dsccommunity/DscWorkshop/) all works as expected. Without adding a prelease version and / or using latest and parameter 'AllowPrerelease', the behavior does not change and nothing breaks.

**Pull request merged**
