### PR TITLE
Add Chocolatey dependency type

### LINKED ISSUE #24: Add chocolatey dependency type
We support PackageManagement, but, that's not exactly recommended over choco.exe at the moment.

### PR DESCRIPTION
**Pull request by pauby**
This will add the Chocolatey dependency type for the Install and Test actions.

Chocolatey needs to be installed first.

Resolves #24

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Hiyo!

I'm up for merging this as long as someone can ack that it works for them - thanks @pauby  : D

**Comment by pauby** [comment]
Let me add in the ability to install Chocolatey if it's not already installed and some tests around it too. Should be a couple of days. 

In the meantime would be great if somebody else could take it for a spin!

**Comment by pauby** [comment]
This is now good to go.

**Comment by raandree** [comment]
@RamblingCookieMonster, can this be merged, please?

**Comment by RamblingCookieMonster** [comment]
Yas!  thanks for the ping, and thanks @pauby  : D

**Comment by RamblingCookieMonster** [comment]
hehe, of course, I don't pin the versions for build modules.  Will try to find time tomorrow or late tonight, sorry!

**Pull request merged**
